apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eodhp-web-presence-database
spec:
  selector:
    matchLabels:
      app: eodhp-web-presence-database
  replicas: 1  # current version only supports one database
  template:
    metadata:
      labels:
        app: eodhp-web-presence-database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.sql_database | default "web_presence_db" }}
            - name: POSTGRES_USER
              value: {{ .Values.database.sql_user | default "admin" }}
            {{- if .Values.database.secretKeys.sqlPasswordKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-presence
                  key:  {{ .Values.database.secretKeys.sqlPasswordKey }}
            {{- else }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.sql_password | default "password" }}
            {{- end }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
              subpath: pgdata

  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage_class | default "standard" }}
        resources:
          requests:
            storage: 1Gi
