apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: {{ .Values.storage_class | default "standard" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
