apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eodhp-website-database
spec:
  selector:
    matchLabels:
      app: eodhp-website-database
  replicas: 3
  template:
    metadata:
      labels:
        app: eodhp-website-database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.sql_database | default "web_presence_db" }}
            - name: POSTGRES_USER
              value: {{ .Values.sql_user | default "admin" }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.sql_password | default "password" }}
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
