{{- $secretName := "django-secret-key" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  # Attempt to get an existing secret
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

  # If the secret doesn't exist, generate a new secret key
  {{- if or (not $existingSecret) (not $existingSecret.data) (not $existingSecret.data "SECRET_KEY") }}
  SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
  {{- else }}
  SECRET_KEY: {{ index $existingSecret.data "SECRET_KEY" }}
  {{- end }}
