{{ if .Values.web.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eodhp-web-presence-ingress
spec:
  ingressClassName: {{.Values.web.ingress.className}}
  rules:
    - host: {{.Values.web.ingress.host}}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: eodhp-web-presence-service
                port:
                  number: 8000
{{ end }}
