apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      containers:
      - name: db-migrate
        image: {{ .Values.image | default "public.ecr.aws/n1b3o1k2/eodhp-web-presence:0.1.6" }}
        command: ["sh", "-c", "python manage.py migrate"]
        env:
          - name: SQL_HOST
            value: {{ .Values.database.sql_host | default "postgres-service" }}
          - name: SQL_PORT
            value: {{ .Values.database.sql_port | default "5432" | quote }}
          - name: SQL_DATABASE
            value: {{ .Values.database.sql_database | default "web_presence_db" }}
          - name: SQL_ENGINE
            value: {{ .Values.database.sql_engine | default "django.db.backends.postgresql_psycopg2" }}
          - name: SQL_USER
            value: {{ .Values.database.sql_user | default "admin" }}
          {{- if .Values.database.existingSecret }}
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-presence
                key:  {{ .Values.database.secretKeys.sqlPasswordKey }}
          {{- else }}
          - name: SQL_PASSWORD
            value: {{ .Values.database.sql_password | default "password" }}
          {{- end }}
          - name: WEB_PRESENCE_STATIC_S3_BUCKET
            value: {{ .Values.aws.static_s3_bucket | default "my_s3_bucket" }}
          - name: AWS_REGION_NAME
            value: {{ .Values.aws.region | default "eu-west-2" }}
          - name: ENVIRONMENT_NAME
            value: {{ .Values.environment.name | default "env" }}
      restartPolicy: OnFailure
  backoffLimit: 10