apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      containers:
      - name: db-migrate
        image: {{ .Values.web.image }}
        command: ["sh", "-c", "python manage.py migrate"]
        envFrom:
            {{- toYaml .Values.web.extraEnvFrom | nindent 12 }}
        env:
          {{- if and (.Values.web.database.secretKeys.sqlPasswordKey) (.Values.web.database.existingSecret) }}
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.web.database.existingSecret }}
                key:  {{ .Values.web.database.secretKeys.sqlPasswordKey }}
          {{- else }}
          - name: SQL_PASSWORD
            value: {{ .Values.web.database.sql_password }}
          {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 10