# Started to implement following guidance from here: https://external-secrets.io/latest/introduction/getting-started/

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      role: arn:aws:iam::   # arn goes here
#      auth:
#        secretRef:
#          accessKeyIDSecretRef:
#            name: web-presence-db-password
#            key: password
#          secretAccessKeySecretRef:
#            name: awssm-secret
#            key: secret-access-key