{{ if .Values.web.serviceAccount.create }}
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount.name }}
  annotations:
    {{- toYaml .Values.web.serviceAccount.annotations | nindent 4 }}
{{ end }}
