{{ if .Values.web.serviceAccount.create }}
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.web.serviceAccount.annotations.roleArn }}
{{ end }}
