apiVersion: v1
kind: Service
metadata:
  name: eodhp-web-presence-service
spec:
  type: ClusterIP
  selector:
    app: eodhp-web-presence
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
