apiVersion: apps/v1
kind: Deployment
metadata:
  name: eodhp-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eodhp-website
  template:
    metadata:
      labels:
        app: eodhp-website
    spec:
      containers:
        - name: eodhp-website
          image: hcollingwoodtpz/eodhp_website:0.1.3
          ports:
            - containerPort: 8000
          env:
            - name: APP_URL
              value: {{ .Values.app_url | default "www.example.com" }}
            - name: SQL_HOST
              value: {{ .Values.sql_host | default "postgres-service" }}
            - name: SQL_PORT
              value: {{ .Values.sql_port | default "5432" | quote }}
            - name: SQL_DATABASE
              value: {{ .Values.sql_database | default "web_presence_db" }}
            - name: SQL_ENGINE
              value: {{ .Values.sql_engine | default "django.db.backends.postgresql_psycopg2" }}
            - name: SQL_USER
              value: {{ .Values.sql_user | default "admin" }}
            - name: SQL_PASSWORD
              value: {{ .Values.sql_password | default "password" }}
